//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/PlayerInputActionMaps.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace RTS.Input
{
    public partial class @PlayerInputActionMaps : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActionMaps()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActionMaps"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""466a91ef-07cc-47c2-a50d-148f7b240da0"",
            ""actions"": [
                {
                    ""name"": ""Open Console"",
                    ""type"": ""Button"",
                    ""id"": ""790354b6-4d38-4add-94f2-9686c5a853d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e719103f-197c-4630-af4d-db363f93b303"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Console"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug Console"",
            ""id"": ""8c844925-9c93-4c71-bb3b-940dd216f61d"",
            ""actions"": [
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""ee31e101-30fe-4f3e-a26f-09a32d0068a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""efdfe22c-9517-4716-a46a-e6d3baa01c68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a9dea757-f97f-4421-88fa-6db36a50d5e4"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dd209ab-db91-4f89-beb6-96b3ee50e412"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_OpenConsole = m_Gameplay.FindAction("Open Console", throwIfNotFound: true);
            // Debug Console
            m_DebugConsole = asset.FindActionMap("Debug Console", throwIfNotFound: true);
            m_DebugConsole_Submit = m_DebugConsole.FindAction("Submit", throwIfNotFound: true);
            m_DebugConsole_Exit = m_DebugConsole.FindAction("Exit", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private IGameplayActions m_GameplayActionsCallbackInterface;
        private readonly InputAction m_Gameplay_OpenConsole;
        public struct GameplayActions
        {
            private @PlayerInputActionMaps m_Wrapper;
            public GameplayActions(@PlayerInputActionMaps wrapper) { m_Wrapper = wrapper; }
            public InputAction @OpenConsole => m_Wrapper.m_Gameplay_OpenConsole;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void SetCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
                {
                    @OpenConsole.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOpenConsole;
                    @OpenConsole.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOpenConsole;
                    @OpenConsole.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOpenConsole;
                }
                m_Wrapper.m_GameplayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @OpenConsole.started += instance.OnOpenConsole;
                    @OpenConsole.performed += instance.OnOpenConsole;
                    @OpenConsole.canceled += instance.OnOpenConsole;
                }
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);

        // Debug Console
        private readonly InputActionMap m_DebugConsole;
        private IDebugConsoleActions m_DebugConsoleActionsCallbackInterface;
        private readonly InputAction m_DebugConsole_Submit;
        private readonly InputAction m_DebugConsole_Exit;
        public struct DebugConsoleActions
        {
            private @PlayerInputActionMaps m_Wrapper;
            public DebugConsoleActions(@PlayerInputActionMaps wrapper) { m_Wrapper = wrapper; }
            public InputAction @Submit => m_Wrapper.m_DebugConsole_Submit;
            public InputAction @Exit => m_Wrapper.m_DebugConsole_Exit;
            public InputActionMap Get() { return m_Wrapper.m_DebugConsole; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DebugConsoleActions set) { return set.Get(); }
            public void SetCallbacks(IDebugConsoleActions instance)
            {
                if (m_Wrapper.m_DebugConsoleActionsCallbackInterface != null)
                {
                    @Submit.started -= m_Wrapper.m_DebugConsoleActionsCallbackInterface.OnSubmit;
                    @Submit.performed -= m_Wrapper.m_DebugConsoleActionsCallbackInterface.OnSubmit;
                    @Submit.canceled -= m_Wrapper.m_DebugConsoleActionsCallbackInterface.OnSubmit;
                    @Exit.started -= m_Wrapper.m_DebugConsoleActionsCallbackInterface.OnExit;
                    @Exit.performed -= m_Wrapper.m_DebugConsoleActionsCallbackInterface.OnExit;
                    @Exit.canceled -= m_Wrapper.m_DebugConsoleActionsCallbackInterface.OnExit;
                }
                m_Wrapper.m_DebugConsoleActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Submit.started += instance.OnSubmit;
                    @Submit.performed += instance.OnSubmit;
                    @Submit.canceled += instance.OnSubmit;
                    @Exit.started += instance.OnExit;
                    @Exit.performed += instance.OnExit;
                    @Exit.canceled += instance.OnExit;
                }
            }
        }
        public DebugConsoleActions @DebugConsole => new DebugConsoleActions(this);
        public interface IGameplayActions
        {
            void OnOpenConsole(InputAction.CallbackContext context);
        }
        public interface IDebugConsoleActions
        {
            void OnSubmit(InputAction.CallbackContext context);
            void OnExit(InputAction.CallbackContext context);
        }
    }
}
